set nocompatible
set nu
set laststatus=2
set termencoding=utf-8
filetype indent plugin on
syntax enable

"#######################
" vundles and their configs
"#######################
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'maksimr/vim-jsbeautify'
Plugin 'preservim/nerdcommenter' " \cc & \cu - works for visual mode
Plugin 'phpactor/phpactor' ,  {'do': 'composer install', 'for': 'php'}
Plugin '907th/vim-auto-save'
Plugin 'vim-syntastic/syntastic'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'msjyoo/vim-autocomplpop-php'
Plugin 'sheerun/vim-polyglot'
Plugin 'dense-analysis/ale'
Plugin 'othree/xml.vim'
Plugin 'neoclide/coc.nvim', {'branch': 'release'}
Plugin 'stephpy/vim-php-cs-fixer'
Plugin 'arnaud-lb/vim-php-namespace'
Plugin 'kien/ctrlp.vim'
"coc debug
"cd ~/.vim/bundle/coc.nvim/ && git reset head --hard
"open vim && :PluginUpdate
"run call coc#util#install()
call vundle#end()

"ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
"ctags
au BufWritePost *.php silent! ! ctags -R --PHP-kinds=cfi --regex-php="/^[ \t]*trait[ \t]+([a-z0_9_]+)/\1/t,traits/i" &
au BufWritePost *.js silent! ! sh -c 'find . -type f -iregex ".*\.js$" -not -path "./node_modules/*" -exec jsctags {} -f \; | sed '/^$/d' | LANG=C sort > ~/.tags' &
set tags+=tags,tags.vendors
"php namespaces
function! IPhpInsertUse()
    call PhpInsertUse()
    call feedkeys('a',  'n')
endfunction
autocmd FileType php inoremap <Leader>u <Esc>:call IPhpInsertUse()<CR>
autocmd FileType php noremap <Leader>u :call PhpInsertUse()<CR>
function! IPhpExpandClass()
    call PhpExpandClass()
    call feedkeys('a', 'n')
endfunction
autocmd FileType php inoremap <Leader>e <Esc>:call IPhpExpandClass()<CR>
autocmd FileType php noremap <Leader>e :call PhpExpandClass()<CR>
autocmd FileType php inoremap <Leader>s <Esc>:call PhpSortUse()<CR>
autocmd FileType php noremap <Leader>s :call PhpSortUse()<CR>
let g:php_namespace_sort_after_insert = 1

"php cs fixer
let g:php_cs_fixer_php_path = "php"               " Path to PHP
let g:php_cs_fixer_enable_default_mapping = 1     " Enable the mapping by default (<leader>pcd)
let g:php_cs_fixer_dry_run = 0                    " Call command with dry-run option
let g:php_cs_fixer_verbose = 0                    " Return the output of command if 1, else an inline information.
autocmd BufWritePost *.php silent! call PhpCsFixerFixFile()
"ale
let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️'
"beautify
map <c-f> :call JsBeautify()<cr> "ctrl-f
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
autocmd FileType json noremap <buffer> <c-f> :call JsonBeautify()<cr>
autocmd FileType jsx noremap <buffer> <c-f> :call JsxBeautify()<cr>
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
"autosave
let g:auto_save = 1
let g:auto_save_events = ["InsertLeave", "TextChanged"]
"syntastic
set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
"let g:syntastic_always_populate_loc_list = 0
"let g:syntastic_auto_loc_list = 0
"let g:syntastic_check_on_open = 0
"let g:syntastic_check_on_wq = 0
let g:syntastic_enable_signs=1
let g:syntastic_enable_highlighting=1
let g:syntastic_echo_current_error=1
let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']
let g:syntastic_mode_map = { 'mode': 'active',
                            \ 'active_filetypes': 
                            \ [
                            \'php',
                            \ 'python', 'javascript'
                            \],
                            \ 'passive_filetypes': [] }
let g:syntastic_javascript_checkers = ['eslint']
"rainbow brackets
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
" Tab control
set expandtab
set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=2 " the visible width of tabs
set softtabstop=2 " edit as if the tabs are 4 characters wide
set shiftwidth=2 " number of spaces to use for indent and unindent
set shiftround " round indent to a multiple of 'shiftwidth'
%retab

"#######################
"undo & backup & history
"#######################

set backup                  " enable backups
set noswapfile
set undodir=~/tmp/undo/     " undo files
set backupdir=~/tmp/backup/ " backups
set directory=~/tmp/swap/   " swap files
set history=1000
set undofile "we like the undo file"
set undolevels=10000
set undoreload=10000
" Make those folders automatically if they don't already exist.
if !isdirectory(expand(&undodir))
  call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
  call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
  call mkdir(expand(&directory), "p")
endif
"no edits in multiple windows, to avoid confusion.
augroup NoSimulataneousEdits
  autocmd!
  autocmd SwapExists * let v:swapchoice= 'o'
  autocmd SwapExists * echomsg ErrorMsg
  autocmd SwapExists * echo 'Duplicate edit session (readonly)'
  autocmd SwapExists * echohl None
augroup END

"#######################
" window resizing
"#######################
function! RESIZEVERT(PlusMinus)
  let num=tabpagewinnr(tabpagenr())
  let pm=a:PlusMinus
  if  num == "2"
    let pm = pm == '+' ? '-' : '+'
  end
  exec "resize " . pm . "1"
endfunction

nnoremap <silent> <DOWN>   :call RESIZEVERT("-")<CR>
nnoremap <silent> <UP> :call RESIZEVERT("+")<CR>
nnoremap <silent> <LEFT> :vertical resize +2<CR>
nnoremap <silent> <RIGHT> :vertical resize -2<CR>

"#######################
" grafix so we can see shit
"#######################

if has("gui_running")
  set guifont=Monaco:h18
  set guifontwide=Hiragino\ Sans\ GB
  set linespace=2
  set background=dark
  colorscheme solarized
endif

"#######################
" PATH var, need ENV for node and composer.
"#######################

let $PATH = '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/basselkhatib/bin:/Users/basselkhatib/.composer/vendor/bin' .':'. $PATH

" Automatically closing braces
inoremap _{ {<CR>}<Esc>ko
inoremap _[ []<Esc>i
inoremap _( ()<Esc>i
inoremap _< <><Esc>i

"general mappings
nnoremap sss :%s/\s\+$//<CR>
nnoremap rrr :source ~/.vimrc<CR>
nnoremap <c-a> :NERDTreeToggle<CR>
nnoremap <c-q> :q!<CR>
nnoremap <c-w> :w!<CR>
nnoremap <c-z> :PluginInstall<CR>
nnoremap <c-x> :PluginClean!<CR>

"When hitting Enter, if the line doesn't start with a /*, insert a semicolon
"inoremap <CR> <C-R>=((match(getline('.'), '\s*/\*')==-1) && (match(getline('.'), '\s*/int')==-1))?';':''<CR><CR>
